server:
  port: 8081
  compression:
    enabled: false # resource 압축
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/your-blog?useSSL=false
    username: root
    password: password
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  servlet:
    multipart:
      file-size-threshold: 3MB
      max-file-size: 3MB
